import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UrqlProvider } from "./urql-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <UrqlProvider>
      <html lang="en" className="dark">
        <body className={`${inter.className} bg-black`}>{children}</body>
      </html>
    </UrqlProvider>
  );
}
